import type { AnsiColorMode, BrailleCell, BrailleRGB } from './types';

// Convert RGB to 256-color xterm index (16-231 6x6x6 color cube + 232-255 grayscale)
export function rgbToAnsi256(r: number, g: number, b: number): number {
  if (r === g && g === b) {
    if (r < 8) return 16;
    if (r > 248) return 231;
    return Math.round(((r - 8) / 247) * 23) + 232;
  }
  const rIdx = Math.round((r / 255) * 5);
  const gIdx = Math.round((g / 255) * 5);
  const bIdx = Math.round((b / 255) * 5);
  return 16 + 36 * rIdx + 6 * gIdx + bIdx;
}

// Convert RGB to 16 standard ANSI colors (0-15)
export function rgbToAnsi16(r: number, g: number, b: number): number {
  const v = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  const isBright = v > 0.5;
  const rBit = r > 128 ? 1 : 0;
  const gBit = g > 128 ? 1 : 0;
  const bBit = b > 128 ? 1 : 0;
  let code = (rBit ? 1 : 0) | (gBit ? 2 : 0) | (bBit ? 4 : 0);
  if (code === 0 && v > 0.2) code = 7; // Gray instead of black
  return isBright ? 90 + code : 30 + code;
}

export function formatBrailleGridToAnsi(
  grid: BrailleCell[][],
  colorMode: AnsiColorMode,
  customHex?: string
): string {
  const RESET = '\x1b[0m';
  const lines: string[] = [];

  for (const row of grid) {
    let line = '';
    let lastFg = '';

    for (const cell of row) {
      if (cell.char === ' ') {
        line += ' ';
        continue;
      }

      let fgCode = '';
      if (colorMode === 'truecolor') {
        fgCode = `\x1b[38;2;${cell.fg.r};${cell.fg.g};${cell.fg.b}m`;
      } else if (colorMode === '256color') {
        const idx = rgbToAnsi256(cell.fg.r, cell.fg.g, cell.fg.b);
        fgCode = `\x1b[38;5;${idx}m`;
      } else if (colorMode === '16color') {
        const code = rgbToAnsi16(cell.fg.r, cell.fg.g, cell.fg.b);
        fgCode = `\x1b[${code}m`;
      } else if (colorMode === 'amber') {
        fgCode = '\x1b[38;2;255;176;0m';
      } else if (colorMode === 'green') {
        fgCode = '\x1b[38;2;0;255;102m';
      } else {
        // Mono
        fgCode = '\x1b[37m';
      }

      if (fgCode !== lastFg) {
        line += fgCode;
        lastFg = fgCode;
      }

      line += cell.char;
    }

    if (lastFg) line += RESET;
    lines.push(line);
  }

  return lines.join('\n');
}

export function formatBrailleGridToPlainText(grid: BrailleCell[][]): string {
  return grid.map(row => row.map(cell => cell.char).join('')).join('\n');
}

export function formatBrailleGridToShellScript(
  grid: BrailleCell[][],
  colorMode: AnsiColorMode
): string {
  const ansiText = formatBrailleGridToAnsi(grid, colorMode);
  const escaped = ansiText.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

  return `#!/usr/bin/env bash
# ================================================================
# GENERATED BY ASCII & DITHER STUDIO ENGINE — ANSI BRAILLE STUDIO
# GitHub: https://github.com/WarunaUdara/custom-ascii-art-tool-oss
# ================================================================

cat << 'EOF'
${ansiText}
EOF
`;
}
